### PR TITLE
Add Readme

### PR DESCRIPTION
**Pull request by duynguyen**

### CODE REVIEW

**Comment by icaraps** [comment]
@duynguyen thanks ! 
I was thinking some parts you wrote should be moved into the https://github.com/adobe-rnd/franklin-customer-project README .
And I was also thinking we should rename (again..) https://github.com/adobe-rnd/franklin-customer-project to https://github.com/adobe-rnd/franklin-default-template or something like that and make it a proper template WDYT ?

**Comment by hannessolo** [comment]
> @duynguyen thanks ! I was thinking some parts you wrote should be moved into the https://github.com/adobe-rnd/franklin-customer-project README . And I was also thinking we should rename (again..) https://github.com/adobe-rnd/franklin-customer-project to https://github.com/adobe-rnd/franklin-default-template or something like that and make it a proper template WDYT ?

I think a template would be great. But maybe we should still keep the customer repo around, as an example with a few components. I don't think that the template should contain any components already.

**Comment by icaraps** [comment]
>  I don't think that the template should contain any components already.

Yup agree. 

> we should still keep the customer repo around

So we would keep it around but use it as what ? A repo where we test things out, for demos etc ? Or are you thinking about something else ?

**Comment by hannessolo** [comment]
> So we would keep it around but use it as what ? A repo where we test things out, for demos etc ? Or are you thinking about something else ?

yes, for demos, or if someone asks “how do I do x”. Maybe we can delete it once we have docs.

**Pull request closed without merging**
